# Generated by Django 3.2.6 on 2021-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_user',
        ),
    ]
