# Generated by Django 3.2.6 on 2021-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Lab_Manager', 'Lab_Manager'), ('Lab_Assistant', 'Lab_Assistant'), ('Lecturer', 'Lecturer'), ('Student', 'Student')], max_length=31),
        ),
    ]
