# Generated by Django 3.2.6 on 2021-09-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_user_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',)},
        ),
    ]
