# Generated by Django 3.2.6 on 2021-08-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_rename_lab_id_lab_id'),
        ('item_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Category',
            new_name='ItemCategory',
        ),
    ]
