# Generated by Django 3.2.6 on 2021-08-31 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_category', '0002_rename_item_category_itemcategory'),
        ('lab', '0003_rename_lab_id_lab_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='display_items')),
                ('description', models.CharField(max_length=1023)),
                ('item_count', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_category.itemcategory')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
