# Generated by Django 3.2.6 on 2021-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayitem',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
