# Generated by Django 3.2.6 on 2021-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_item', '0002_alter_displayitem_item_count'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='displayitem',
            table='display_item',
        ),
    ]
