# Generated by Django 3.2.6 on 2021-09-18 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0004_alter_lab_table'),
        ('display_item', '0003_alter_displayitem_table'),
        ('lecturer_user', '0001_initial'),
        ('student_user', '0002_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1023)),
                ('state', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='New', max_length=31)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer_user.lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_user.student')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quentity', models.IntegerField()),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='PENDING', max_length=31)),
                ('display_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display_item.displayitem')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_user.student')),
            ],
            options={
                'db_table': 'request_item',
            },
        ),
    ]
