# Generated by Django 3.2.6 on 2021-09-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_item', '0003_alter_displayitem_table'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestitem',
            old_name='quentity',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('request', 'display_item')},
        ),
    ]
