# Generated by Django 3.2.6 on 2021-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210919_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=31),
        ),
    ]
