# Generated by Django 3.2.6 on 2021-10-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Declined by Lab', 'Declined by Lab')], default='Pending', max_length=31),
        ),
    ]
