# Generated by Django 3.2.6 on 2021-08-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='department_id',
            new_name='department',
        ),
    ]
