# Generated by Django 3.2.6 on 2021-08-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rename_department_id_lab_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='lab_id',
            new_name='id',
        ),
    ]
