# Generated by Django 3.2.6 on 2021-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_rename_lab_id_lab_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lab',
            table='lab',
        ),
    ]
