# Generated by Django 3.2.6 on 2021-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_user',
        ),
    ]
